# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HomdLRPNqpuT38b5JRkwH6oonkIbRp8p
"""

!pip install kmodes

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN, SpectralClustering
from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
import joblib

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Wholesale customers data.csv")
df.head()

df.info()
df.describe()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

df.hist(figsize=(12,10), bins=20)
plt.suptitle("Feature Distributions")
plt.show()

X = df.drop(['Channel','Region'], axis=1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertia = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.plot(range(1, 11), inertia, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.show()

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.scatter(X_pca[:,0], X_pca[:,1])
plt.title("PCA Projection (2D)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans_labels = kmeans.fit_predict(X_scaled)

agg = AgglomerativeClustering(n_clusters=3)
agg_labels = agg.fit_predict(X_scaled)

dbscan = DBSCAN(eps=0.8, min_samples=5)
db_labels = dbscan.fit_predict(X_scaled)

gmm = GaussianMixture(n_components=3, random_state=42)
gmm_labels = gmm.fit_predict(X_scaled)

spectral = SpectralClustering(n_clusters=3, assign_labels='kmeans', random_state=42)
spec_labels = spectral.fit_predict(X_scaled)

plt.scatter(X_pca[:,0], X_pca[:,1], c=kmeans_labels)
plt.title("K-Means Clusters")
plt.show()

plt.scatter(X_pca[:,0], X_pca[:,1], c=agg_labels)
plt.title("Hierarchical Clusters")
plt.show()

plt.scatter(X_pca[:,0], X_pca[:,1], c=db_labels)
plt.title("DBSCAN Clusters")
plt.show()

scores = []

scores.append(silhouette_score(X_scaled, kmeans_labels))
scores.append(silhouette_score(X_scaled, agg_labels))
scores.append(silhouette_score(X_scaled, gmm_labels))
scores.append(silhouette_score(X_scaled, spec_labels))

models = ["KMeans", "Agglomerative", "GMM", "Spectral"]

plt.bar(models, scores)
plt.title("Silhouette Score Comparison")
plt.ylabel("Score")
plt.show()

for model, score in zip(models, scores):
    print(model, ":", score)

joblib.dump(kmeans, "kmeans_model.pkl")
joblib.dump(scaler, "scaler.pkl")